name: jankaiponen
favicon: null
layout_spectrum: 0.7432495073881
typography_spectrum: 0.8651277180761099
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.45445102150551975
  lightness: 0.7417361217085272
  saturation: 0.5121614225208759
  rhythmicContrast: 0.4714872685726732
purpose: []
